# Generated by Django 3.0.3 on 2020-08-20 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('technology', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=255)),
                ('capability', models.CharField(max_length=255)),
                ('applicant_status', models.CharField(default='NOT FILLED', max_length=255)),
                ('date_posted', models.DateField(default=datetime.date.today)),
                ('expiry_date', models.DateField()),
                ('applicant', models.IntegerField(default=0)),
                ('manager', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
