# Generated by Django 3.0.3 on 2020-08-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0002_challenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='applicant_status',
            field=models.CharField(blank=True, default='NOT_FILLED', max_length=255),
        ),
    ]
