# Generated by Django 3.0.3 on 2020-08-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0004_auto_20200821_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='applicant_status',
            field=models.CharField(default='0000000', editable=False, max_length=7),
        ),
    ]
