# Generated by Django 3.0.3 on 2020-08-20 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0005_auto_20200821_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='applicant_status',
        ),
    ]
