# Generated by Django 3.0.3 on 2020-08-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0006_remove_challenges_applicant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='applicant_status',
            field=models.CharField(default='NOT FILLED', max_length=255),
        ),
    ]
