# Generated by Django 3.0.3 on 2020-08-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0009_auto_20200823_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedchallenges',
            name='challenge',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appliedchallenges',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
