# Generated by Django 3.0.3 on 2020-08-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20200817_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='role',
            field=models.CharField(blank=True, default='employee', max_length=100, null=True),
        ),
    ]
