# Generated by Django 3.0.3 on 2020-08-17 20:04

import basic_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20200817_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=basic_app.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='role',
            field=models.CharField(default='employee', max_length=100),
        ),
    ]
