# Generated by Django 3.0.3 on 2020-08-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20200819_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='role',
            field=models.CharField(choices=[('A', 'admin'), ('E', 'employee')], default='E', max_length=128),
        ),
    ]
